### ISSUE TITLE
Kill statistics

### ISSUE THREAD

**Issue by emilekm** [avramovic/PRstats#1]
I noticed that the service has gone up again and is already attracting people with K/D mindset.

I'd like to ask to consider hiding all statistics regarding K/D (or only kills). I remember last time the service was up, people were more focused on getting kills than teamworking, reviving people and generally having fun. They'd rather follow up on kills than revive their squad mates and get the kills together. People bloating their K/D in allchat was normal practice.

I understand that K/D and points are the only statistics you can extract from PRSPY but it brings bad vibes to PR community. Maybe you'll be interested in extracting data from PRdemo files. I've been working on a [lib](https://github.com/emilekm/pr-demo-analyzer) for easy reading of those files (in Python). There are multiple in-game events in these files.

Disclaimer: my K/D is mostly positive, above average ;).

Cheers,
cassius23 (PR name)

**Comment by avramovic** [comment]
Really? How did you even find it? I never announced anywhere it's up and running again. This was a weekend-project to upgrade underlying Laravel framework and update the parser to support new PRSpy output format. Ok, I've tried to add match tracking but never finished it completely, hence there's no announcement as the DB might be reset anytime.

I understand your concerns, though I don't understand such people (chasing kills). Look at my K/D ratio! I show it with dignity! Medic forever! 😄 

Your lib seems great, but I have no idea how could I use it in a PHP project. It would be great if I had time to rewrite it to PHP and extract data from prdemo files, that would provide much more stats. Do you know if prdemo files are stored on users' computers or on servers? I'm not near my gaming (Windows) PC right now so I can't check.

If I remove kills and deaths, the site kind of loses its point of existence... not that if has a strong one right now 😄 Maybe remove it from user lists but keep them in clan/match pages?

**Comment by AlonTavor** [comment]
prdemos are hosted by the servers. There's no standard API for retrieving them.
Example:
https://eu1.prta.co/servers/prbf2/1/tracker/ (direct link in query string)
http://br.hogclangaming.com/pr1/ (BF2 battlerecorder in here too)

Ungzip, then parse according to
https://docs.google.com/spreadsheets/d/1ArciEg1rkG_MHzSYWphje1s071a6kD2ojuD58nVmwAE/edit#gid=1007827128
